// Generated by `bun init`

declare module "bun" {
  interface Env {
    DISPATCH_NAMESPACE: string;
		DATABASE_URL: string;
		GITHUB_USER_REPO_TOKEN: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_EMAIL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		DB_ENCRYPTION_KEY: string;
		BETTER_AUTH_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		GITHUB_WEBHOOK_SECRET: string;
		GITHUB_INSTALLATION_LINK: string;
		GITHUB_PRIVATE_KEY_BASE64: string;
		GITHUB_APP_ID: string;
		ENABLE_SIGNUP: string;
  }
}

interface User {
	id: string;
	email: string;
	name: string;
}


declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
