/**
 * Error codes as string constants all accessible through the ErrorCode enum.
 * Has prefix MODULE.FUNCTION.ERROR_CODE
 */
export enum ErrorCode {
    // CONTROLLER
    CONTROLLER_DATA_GET_FAILED = 'CONTROLLER.DATA.GET.FAILED',
    CONTROLLER_DATASTORE_CREATE_FAILED = 'CONTROLLER.DATASTORE.CREATE.FAILED',
    CONTROLLER_DATASTORE_CREATE_UNIQUE_NAME = 'CONTROLLER.DATASTORE.CREATE.UNIQUE_NAME',
    CONTROLLER_DATASTORE_DELETE_FAILED = 'CONTROLLER.DATASTORE.DELETE.FAILED',
    CONTROLLER_DATASTORE_DELETE_NOT_FOUND = 'CONTROLLER.DATASTORE.DELETE.NOT_FOUND',
    CONTROLLER_DATASTORE_SCHEMA_CHANGE_FAILED = 'CONTROLLER.DATASTORE.SCHEMA_CHANGE.FAILED',
    CONTROLLER_DATASTORE_SCHEMA_CHANGE_NOT_FOUND = 'CONTROLLER.DATASTORE.SCHEMA_CHANGE.NOT_FOUND',
    CONTROLLER_DATASTORE_UPDATE_FAILED = 'CONTROLLER.DATASTORE.UPDATE.FAILED',
    CONTROLLER_DATASTORE_UPDATE_NOT_FOUND = 'CONTROLLER.DATASTORE.UPDATE.NOT_FOUND',
    CONTROLLER_DATASTORE_UPDATE_UNIQUE_NAME = 'CONTROLLER.DATASTORE.UPDATE.UNIQUE_NAME',
    CONTROLLER_DATASTORE_TABLE_GET_FAILED = 'CONTROLLER.DATASTORE.TABLE.GET.FAILED',
    CONTROLLER_DATASTORE_TABLE_NOT_FOUND = 'CONTROLLER.DATASTORE.TABLE.NOT_FOUND',
    CONTROLLER_DATASTORE_TABLE_INVALID_FILTER = 'CONTROLLER.DATASTORE.TABLE.INVALID_FILTER',
    CONTROLLER_DATASTORE_TABLE_INSERT_FAILED = 'CONTROLLER.DATASTORE.TABLE.INSERT.FAILED',
    CONTROLLER_DATASTORE_TABLE_INSERT_INVALID_COLUMNS = 'CONTROLLER.DATASTORE.TABLE.INSERT.INVALID_COLUMNS',
    CONTROLLER_DATASTORE_TABLE_UPDATE_FAILED = 'CONTROLLER.DATASTORE.TABLE.UPDATE.FAILED',
    CONTROLLER_DATASTORE_TABLE_UPDATE_NO_FILTERS = 'CONTROLLER.DATASTORE.TABLE.UPDATE.NO_FILTERS',
    CONTROLLER_DATASTORE_TABLE_DELETE_FAILED = 'CONTROLLER.DATASTORE.TABLE.DELETE.FAILED',
    CONTROLLER_DATASTORE_TABLE_DELETE_NO_FILTERS = 'CONTROLLER.DATASTORE.TABLE.DELETE.NO_FILTERS',
    CONTROLLER_MCP_KEYS_LIST_FAILED = 'CONTROLLER.MCP.KEYS.LIST.FAILED',
    CONTROLLER_MCP_KEY_CREATE_FAILED = 'CONTROLLER.MCP.KEY.CREATE.FAILED',
    CONTROLLER_MCP_KEY_DELETE_FAILED = 'CONTROLLER.MCP.KEY.DELETE.FAILED',
    CONTROLLER_MCP_KEY_DELETE_NOT_FOUND = 'CONTROLLER.MCP.KEY.DELETE.NOT_FOUND',
    CONTROLLER_MCP_KEY_UPDATE_FAILED = 'CONTROLLER.MCP.KEY.UPDATE.FAILED',
    CONTROLLER_MCP_KEY_UPDATE_NOT_FOUND = 'CONTROLLER.MCP.KEY.UPDATE.NOT_FOUND',
    // SUBROUTINES
    SR_DATASTORE_CREATE_FAILED = 'SR.DATASTORE.CREATE.FAILED',
    SR_DATASTORE_DELETE_FAILED = 'SR.DATASTORE.DELETE.FAILED',
    SR_DATASTORE_ROLLBACK_DELETE_FILE_FAILED = 'SR.DATASTORE.ROLLBACK.DELETE_FILE_FAILED',
    SR_DATASTORE_GET_SCHEMA_FAILED = 'SR.DATASTORE.GET_SCHEMA.FAILED',
    SR_DATASTORE_OPEN_CONNECTION_FAILED = 'SR.DATASTORE.OPEN_CONNECTION.FAILED',
    SR_DATASTORE_QUERY_BUILD_FAILED = 'SR.DATASTORE.QUERY_BUILD.FAILED',
    SR_DATASTORE_QUERY_EXECUTION_FAILED = 'SR.DATASTORE.QUERY_EXECUTION.FAILED',
    SR_DATASTORE_INSERT_ROWS_FAILED = 'SR.DATASTORE.INSERT_ROWS.FAILED',
    SR_DATASTORE_UPDATE_ROWS_FAILED = 'SR.DATASTORE.UPDATE_ROWS.FAILED',
    SR_DATASTORE_DELETE_ROWS_FAILED = 'SR.DATASTORE.DELETE_ROWS.FAILED',
    SR_DATASTORE_VALIDATE_ROW_DATA_FAILED = 'SR.DATASTORE.VALIDATE_ROW_DATA.FAILED',
  }
  