/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: string | null;
  accountId: string;
  createdAt: string;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: string | null;
  scope: string | null;
  updatedAt: string;
  userId: string;
}

export interface Apikey {
  createdAt: string;
  enabled: number | null;
  expiresAt: string | null;
  id: string;
  key: string;
  lastRefillAt: string | null;
  lastRequest: string | null;
  metadata: string | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: number | null;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number | null;
  start: string | null;
  updatedAt: string;
  userId: string;
}

export interface Datastore {
  created_at: Generated<string>;
  encrypted_json: string | null;
  external_id: string;
  external_name: string;
  id: string;
  internal_name: string;
  last_accessed_at: string | null;
  metadata_json: string | null;
  organization_id: string;
  provider: string;
  provisioned_at: string | null;
  region: string | null;
  schema_json: string;
  status: Generated<string | null>;
  updated_at: Generated<string>;
}

export interface Invitation {
  email: string;
  expiresAt: string;
  id: string;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface Log {
  app_id: string | null;
  chat_id: string | null;
  created_at: Generated<string>;
  environment: string | null;
  error_entry: string | null;
  id: Generated<number>;
  is_resolved: Generated<number | null>;
  level: string;
  message: string;
  metadata: string | null;
  needs_action: string | null;
  organization_id: string | null;
  request_id: string | null;
  resolved_at: string | null;
  service_id: string | null;
  service_resource_id: string | null;
  updated_at: Generated<string>;
  user_id: string | null;
  workflow_id: string | null;
}

export interface Mcpkey {
  created_at: Generated<string>;
  id: string;
  internal_name: string;
  organization_id: string;
  updated_at: Generated<string>;
  user_id: string;
}

export interface Member {
  createdAt: string;
  id: string;
  organizationId: string;
  role: string;
  userId: string;
}

export interface Migration {
  applied_at: Generated<string>;
  filename: string;
}

export interface Organization {
  createdAt: string;
  id: string;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface PermissionAction {
  i18n_description: string;
  i18n_title: string;
  id: string;
}

export interface PermissionAllowedActionByType {
  id: Generated<number>;
  permission_action_id: string;
  permission_type_id: string;
}

export interface PermissionMapping {
  created_at: Generated<string>;
  id: Generated<number>;
  mcpkey_id: string | null;
  permission_action_id: string;
  permission_target_id: string;
  permission_target_org_id: string;
  user_id: string | null;
}

export interface PermissionTarget {
  created_at: Generated<string>;
  datastore_id: string | null;
  id: string;
  internal_name: string;
  organization_id: string;
  permission_type_id: string;
}

export interface PermissionType {
  i18n_description: string;
  i18n_title: string;
  id: string;
}

export interface Session {
  activeOrganizationId: string | null;
  createdAt: string;
  expiresAt: string;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: string;
  userAgent: string | null;
  userId: string;
}

export interface User {
  banExpires: string | null;
  banned: number | null;
  banReason: string | null;
  createdAt: string;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: string;
}

export interface Verification {
  createdAt: string;
  expiresAt: string;
  id: string;
  identifier: string;
  updatedAt: string;
  value: string;
}

export interface DB {
  account: Account;
  apikey: Apikey;
  datastore: Datastore;
  invitation: Invitation;
  log: Log;
  mcpkey: Mcpkey;
  member: Member;
  migration: Migration;
  organization: Organization;
  permission_action: PermissionAction;
  permission_allowed_action_by_type: PermissionAllowedActionByType;
  permission_mapping: PermissionMapping;
  permission_target: PermissionTarget;
  permission_type: PermissionType;
  session: Session;
  user: User;
  verification: Verification;
}
